services:
  - type: web
    name: django-todo-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todoproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tododb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
databases:
  - name: tododb
    plan: free